/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/app-header.vue')['default']
    AppTabBar: typeof import('./src/components/app-tab-bar.vue')['default']
    ConfirmDialog: typeof import('./src/components/confirm-dialog.vue')['default']
    CoverImage: typeof import('./src/components/cover-image.vue')['default']
    CreateActionSheet: typeof import('./src/components/create-action-sheet.vue')['default']
    LogoutDialog: typeof import('./src/components/logout-dialog.vue')['default']
    PasscodeSheet: typeof import('./src/components/passcode-sheet.vue')['default']
    PlaceCoverImage: typeof import('./src/components/place-cover-image.vue')['default']
    PlanGeneratingMap: typeof import('./src/components/plan-generating-map.vue')['default']
    ProfileMenuSheet: typeof import('./src/components/profile-menu-sheet.vue')['default']
    ProfileNavBar: typeof import('./src/components/profile-nav-bar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TripCard: typeof import('./src/components/trip-card.vue')['default']
    TripChatSheet: typeof import('./src/components/trip-chat-sheet.vue')['default']
    TripDayItinerary: typeof import('./src/components/trip-day-itinerary.vue')['default']
    TripDetailMap: typeof import('./src/components/trip-detail-map.vue')['default']
    TripHeroPhoto: typeof import('./src/components/trip-hero-photo.vue')['default']
    TripMapPanel: typeof import('./src/components/trip-map-panel.vue')['default']
    TripNoteSheet: typeof import('./src/components/trip-note-sheet.vue')['default']
    TripOverviewBody: typeof import('./src/components/trip-overview-body.vue')['default']
    TripOverviewMap: typeof import('./src/components/trip-overview-map.vue')['default']
    TripPackSheet: typeof import('./src/components/trip-pack-sheet.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanFloatingPanel: typeof import('vant/es')['FloatingPanel']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPopup: typeof import('vant/es')['Popup']
    VanSearch: typeof import('vant/es')['Search']
  }
}
